classdef FailureCode
  properties (Constant)
    OK = 0
    FAIL_GENERIC = -1
    FAIL_MISSING_TEST_DATA = -2
    FAIL_ERROR_IN_CALLED_FUNC = -3
    FAIL_EXCEPTION = -4
    FAIL_MEMORY_EXCEPTION = -5
    FAIL_ARITHM_EXCEPTION = -6
    FAIL_MEMORY_CORRUPTION_BEGIN = -7
    FAIL_MEMORY_CORRUPTION_END = -8
    FAIL_MEMORY_LEAK = -9
    FAIL_INVALID_OUTPUT = -10
    FAIL_MISMATCH = -11
    FAIL_BAD_ACCURACY = -12
    FAIL_HANG = -13
    FAIL_BAD_ARG_CHECK = -14
    FAIL_INVALID_TEST_DATA = -15
    SKIPPED = 1
  end
end
