classdef ImwritePNGFlags
  properties (Constant)
    IMWRITE_PNG_STRATEGY_DEFAULT = 0
    IMWRITE_PNG_STRATEGY_FILTERED = 1
    IMWRITE_PNG_STRATEGY_HUFFMAN_ONLY = 2
    IMWRITE_PNG_STRATEGY_RLE = 3
    IMWRITE_PNG_STRATEGY_FIXED = 4
  end
end
