classdef ImwriteFlags
  properties (Constant)
    IMWRITE_JPEG_QUALITY = 1
    IMWRITE_JPEG_PROGRESSIVE = 2
    IMWRITE_JPEG_OPTIMIZE = 3
    IMWRITE_JPEG_RST_INTERVAL = 4
    IMWRITE_JPEG_LUMA_QUALITY = 5
    IMWRITE_JPEG_CHROMA_QUALITY = 6
    IMWRITE_PNG_COMPRESSION = 16
    IMWRITE_PNG_STRATEGY = 17
    IMWRITE_PNG_BILEVEL = 18
    IMWRITE_PXM_BINARY = 32
    IMWRITE_WEBP_QUALITY = 64
  end
end
