classdef FeatureSet
  properties (Constant)
    FEATURE_SET_COMPUTE_10 = 10
    FEATURE_SET_COMPUTE_11 = 11
    FEATURE_SET_COMPUTE_12 = 12
    FEATURE_SET_COMPUTE_13 = 13
    FEATURE_SET_COMPUTE_20 = 20
    FEATURE_SET_COMPUTE_21 = 21
    FEATURE_SET_COMPUTE_30 = 30
    FEATURE_SET_COMPUTE_32 = 32
    FEATURE_SET_COMPUTE_35 = 35
    FEATURE_SET_COMPUTE_50 = 50
    GLOBAL_ATOMICS = 10
    SHARED_ATOMICS = 11
    NATIVE_DOUBLE = 12
    WARP_SHUFFLE_FUNCTIONS = 13
    DYNAMIC_PARALLELISM = 14
  end
end
